services:
  clash:
    image: metacubex/mihomo:latest
    container_name: clash
    volumes:
      - ./config.yaml:/root/.config/mihomo/config.yaml:ro
    network_mode: host
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  yacd:
    image: asnil/yacd-meta:latest
    container_name: yacd
    ports:
      - 9099:80
    restart: unless-stopped
