services:
  clash:
    image: metacubex/clash-meta:latest
    container_name: clash
    volumes:
      - ./config.yaml:/root/.config/clash/config.yaml:ro
      - ./ui:/ui
    network_mode: host
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
