services:
  gitea:
    image: gitea/gitea:1
    container_name: gitea
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
      - 222:22
    restart: unless-stopped
