services:
  unblock-netease-music:
    image: pan93412/unblock-netease-music-enhanced:latest
    container_name: unblock-netease-music
    environment:
      NODE_ENV: production
      ENABLE_FLAC: true
      ENABLE_LOCAL_VIP: svip
      FOLLOW_SOURCE_ORDER: true
    command: ['-s', '-o', 'ytdlp', 'kugou']
    ports:
      - 80:8080
    restart: always
