services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    ports:
      - 1883:1883     # MQTT
      # - 9001:9001   # WebSocket
    restart: unless-stopped
