services:
  coredns:
    image: coredns/coredns:latest
    container_name: coredns
    ports:
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - ./Corefile:/etc/coredns/Corefile
      - ./hosts:/etc/coredns/hosts:ro
    command: ['-conf', '/etc/coredns/Corefile']
    restart: unless-stopped
