services:
  coredns:
    image: coredns/coredns:latest
    container_name: coredns
    ports:
      - 5353:5353/tcp
      - 5353:5353/udp
    volumes:
      - ./Corefile:/etc/coredns/Corefile
      - ./hosts:/etc/hosts:ro
    command: ['-conf', '/etc/coredns/Corefile']
    restart: unless-stopped
