services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    expose:
      - 3000
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
