services:
  headscale:
    image: headscale/headscale:latest
    container_name: headscale
    command: ['headscale', 'serve']
    ports:
      - 8080:8080
      - 9090:9090
    volumes:
      - ./config:/etc/headscale/
    restart: unless-stopped
