services:
  alist:
    image: xhofe/alist:latest
    container_name: alist
    volumes:
      - ./data:/opt/alist/data
      - ./public:/public
    ports:
      - 5244:5244
    environment:
      PUID: 0
      PGID: 0
      UMASK: 022
    restart: always
