services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    ports:
      - 9443:9443
      # The 8000 port is optional and is only required if you plan to use the Edge compute features with Edge agents.
      # https://docs.portainer.io/start/install-ce/server/docker/linux
      # - 8000:8000
    restart: always
