services:
  obsidian-livesync-db:
    image: couchdb:latest
    container_name: obsidian-livesync-db
    environment:
      COUCHDB_USER: ${OBSIDIAN_LIVESYNC_USER}
      COUCHDB_PASSWORD: ${OBSIDIAN_LIVESYNC_PASSWORD}
    ports:
      - 5984:5984
    volumes:
      - ./couchdb:/opt/couchdb/data
    restart: unless-stopped
